jobs:  
#  - name: nginx-manifest
#    type: manifest
#    steps:
#      - IN: nginx-image
#      - IN: trigger

  - name: ddc-deploy_migrate
    type: deploy
    steps:
      - IN: nginx-manifest
      - IN: ddc-cluster_migrate
      - TASK: managed
